# Theme metadata
name = "Splitview"
license = "MIT"
licenselink = "https://github.com/yourusername/splitview/blob/master/LICENSE"
description = "A split-screen Hugo theme for social media micro-posts"
homepage = "https://github.com/yourusername/splitview"
min_version = "0.80.0"

[author]
  name = "Greg Morris"

